name: GCP Terraform Destroy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform-destroy:
    runs-on: self-hosted

    steps:

      # 1. Checkout Repository
      - name: Checkout
        uses: actions/checkout@v4


      # 2. Authenticate to Google Cloud using WIF
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/346137993404/locations/global/workloadIdentityPools/github-actions-pool-01/providers/github-actions-provider"
          service_account: "github-actions-sa@jitu-dev-project-2026.iam.gserviceaccount.com"
          project_id: "jitu-dev-project-2026"


      # 3. Setup Google Cloud CLI
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v3
        with:
          skip_install: true


      # 4. Verify GCP Authentication
      - name: Verify GCP Authentication
        shell: powershell
        run: |
          Write-Host "===== Active GCP Account ====="
          gcloud auth list

          Write-Host "===== Current GCP Project ====="
          gcloud config get-value project

          Write-Host "===== GCP Project Test ====="
          gcloud projects describe jitu-dev-project-2026 --format="value(projectId)"


      # 5. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false


      # 6. Check Terraform
      - name: Check Terraform
        shell: powershell
        run: |
          Write-Host "===== Terraform Location ====="
          where.exe terraform

          Write-Host "===== Terraform Version ====="
          terraform version


      # 7. Terraform Init
      - name: Terraform Init
        working-directory: ./Fed-deploy/Environment/Uat
        shell: powershell
        run: terraform init -input=false -no-color


      # 8. Terraform Validate
      - name: Terraform Validate
        working-directory: ./Fed-deploy/Environment/Uat
        shell: powershell
        run: terraform validate -no-color


      # 9. Terraform Destroy Plan
      - name: Terraform Destroy Plan
        working-directory: ./Fed-deploy/Environment/Uat
        shell: powershell
        run: terraform plan -destroy -input=false -no-color


      # 10. Terraform Destroy
      - name: Terraform Destroy
        working-directory: ./Fed-deploy/Environment/Uat
        shell: powershell
        run: terraform destroy -auto-approve -input=false -no-color