name: GCP Terraform CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  gcp-auth-test:
    runs-on: self-hosted

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/346137993404/locations/global/workloadIdentityPools/github-actions-pool-01/providers/github-actions-provider'
          service_account: 'github-actions-sa@jitu-dev-project-2026.iam.gserviceaccount.com'

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v3
        with:
          skip_install: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        working-directory: ./Fed-deploy/Environment/Uat
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: ./Fed-deploy/Environment/Uat
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./Fed-deploy/Environment/Uat
        run: terraform plan -input=false